#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    sp-ueb-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "sp-ueb-redirectHttps"
    sp-ueb-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "sp-ueb-redirectHttps"
    sp-ueb-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "sp-ueb-redirectHttps"
    
    
    sp-ueb-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    sp-ueb-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-web-80"
      ruleSyntax: v3
      
      tls: true
      
    sp-ueb-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^sp-ueb\.ddev\.site$`)
      
      service: "sp-ueb-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    sp-ueb-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    sp-ueb-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-sp-ueb-xhgui:80
        
    
    sp-ueb-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-sp-ueb-web:80
        
    sp-ueb-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-sp-ueb-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/sp-ueb.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/sp-ueb.key