base: 'https://ueberland-tecklenburg.de'
baseVariants:
  -
    base: 'https://site-ueberland.ddev.site'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=1'
languages:
  -
    title: Deutsch
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
    deeplTargetLanguage: DE
    websiteTitle: ''
  -
    title: Englisch
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: '0'
    flag: gb
    languageId: 1
    websiteTitle: ''
    deeplTargetLanguage: EN-US
rootPageId: 1
routeEnhancers:
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 109
    routes:
      -
        routePath: '/{localized_seite}/{page}'
        _controller: 'News::list'
        _arguments:
          page: currentPage
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      localized_seite:
        type: LocaleModifier
        default: seite
        localeMap:
          -
            locale: 'en_.*'
            value: page
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
  UeberlandPluginShow:
    type: Extbase
    extension: ueberland
    plugin: ueberland
    limitToPages:
      - 61
    routes:
      -
        routePath: '/{angebot_slug}'
        _controller: 'Angebot::show'
        _arguments:
          angebot_slug: angebot
    defaultController: 'Angebot::show'
    aspects:
      angebot_slug:
        type: PersistedAliasMapper
        tableName: tx_ueberland_domain_model_angebot
        routeFieldName: slug
  UeberlandPluginList:
    type: Extbase
    extension: ueberland
    plugin: ueberland
    limitToPages:
      - 18
    routes:
      -
        routePath: '/{localized_bundesland}/{bundesland_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
      -
        routePath: '/{localized_bundesland}/{bundesland_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          page: currentPage
      -
        routePath: '/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          category_slug: category
      -
        routePath: '/{localized_category}/{category_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          category_slug: category
          page: currentPage
      -
        routePath: '/{localized_land}/{land_slug}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
      -
        routePath: '/{localized_land}/{land_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          page: currentPage
      -
        routePath: '/{localized_stadt}/{stadt_slug}'
        _controller: 'Angebot::list'
        _arguments:
          stadt_slug: city
      -
        routePath: '/{localized_stadt}/{stadt_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          stadt_slug: city
          page: currentPage
      -
        routePath: '/{localized_land}/{land_slug}/{localized_bundesland}/{bundesland_slug}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          bundesland_slug: section
      -
        routePath: '/{localized_land}/{land_slug}/{localized_bundesland}/{bundesland_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          bundesland_slug: section
          page: currentPage
      -
        routePath: '/{localized_land}/{land_slug}/{localized_stadt}/{stadt_slug}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          stadt_slug: city
      -
        routePath: '/{localized_land}/{land_slug}/{localized_stadt}/{stadt_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          stadt_slug: city
          page: currentPage
      -
        routePath: '/{localized_land}/{land_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          category_slug: category
      -
        routePath: '/{localized_land}/{land_slug}/{localized_category}/{category_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          category_slug: category
          page: currentPage
      -
        routePath: '/{localized_land}/{land_slug}/{localized_category}/{category_slug}/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          category_slug: category
          page: currentPage
      -
        routePath: 'bundesland/{bundesland_slug}/{localized_stadt}/{stadt_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          stadt_slug: city
      -
        routePath: '/{localized_bundesland}/{bundesland_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          category_slug: category
      -
        routePath: '/{localized_stadt}/{stadt_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          stadt_slug: city
          category_slug: category
      -
        routePath: '/{localized_land}/{land_slug}/{localized_bundesland}/{bundesland_slug}/{localized_stadt}/{stadt_slug}'
        _controller: 'Angebot::list'
        _arguments:
          land_slug: country
          bundesland_slug: section
          stadt_slug: city
      -
        routePath: '/{localized_land}/{land_slug}/{localized_bundesland}/{bundesland_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          category_slug: category
          land_slug: country
      -
        routePath: '/{localized_land}/{land_slug}/{localized_stadt}/{stadt_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          category_slug: category
          land_slug: country
          stadt_slug: city
      -
        routePath: '/{localized_bundesland}/{bundesland_slug}/{localized_stadt}/{stadt_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          category_slug: category
          stadt_slug: city
      -
        routePath: '/{localized_land}/{land_slug}/{localized_bundesland}/{bundesland_slug}/{localized_stadt}/{stadt_slug}/{localized_category}/{category_slug}'
        _controller: 'Angebot::list'
        _arguments:
          bundesland_slug: section
          category_slug: category
          land_slug: country
          stadt_slug: city
      -
        routePath: '/{localized_seite}/{page}'
        _controller: 'Angebot::list'
        _arguments:
          page: currentPage
    defaultController: 'Angebot::list'
    defaults:
      page: '0'
    aspects:
      category_slug:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      land_slug:
        type: PersistedAliasMapper
        tableName: tx_ueberland_domain_model_land
        routeFieldName: slug
      bundesland_slug:
        type: PersistedAliasMapper
        tableName: tx_ueberland_domain_model_bundesland
        routeFieldName: slug
      stadt_slug:
        type: PersistedAliasMapper
        tableName: tx_ueberland_domain_model_stadt
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      localized_bundesland:
        type: LocaleModifier
        default: bundesland
        localeMap:
          -
            locale: 'en_.*'
            value: section
      localized_category:
        type: LocaleModifier
        default: kategorie
        localeMap:
          -
            locale: 'en_.*'
            value: category
      localized_land:
        type: LocaleModifier
        default: land
        localeMap:
          -
            locale: 'en_.*'
            value: country
      localized_stadt:
        type: LocaleModifier
        default: stadt
        localeMap:
          -
            locale: 'en_.*'
            value: city
      localized_seite:
        type: LocaleModifier
        default: seite
        localeMap:
          -
            locale: 'en_.*'
            value: page
websiteTitle: ''
